name: "Add Labels Action"
description: "add-labels-action"

inputs:
  github_owner:
    description: "Owner of the repository"
    default: ${{ github.repository_owner }}
  github_repo:
    description: "Repository name"
    default: ${{ github.event.repository.name }}
  github_token:
    description: "GitHub token"
    default: ${{ github.token }}
  github_pr_number:
    description: "GitHub PR number"
    default: ${{ github.event.pull_request.number }}
  github_pr_title:
    description: "GitHub PR title"
    default: ${{ github.event.pull_request.title }}

runs:
  using: "composite"
  steps:
    - name: Get current labels from PR
      id: get_labels
      shell: bash
      working-directory: src/labels
      run: ./get.sh
      env:
        GITHUB_REPOSITORY: ${{ inputs.github_owner }}/${{ inputs.github_repo }}
        GITHUB_ISSUE_NUMBER: ${{ inputs.github_pr_number }}
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Construct labels to add/delete
      id: construct_labels
      working-directory: .github/.scripts
      shell: bash
      run: ./construct_labels.sh
      env:
        REPO: ${{ inputs.github_owner }}/${{ inputs.github_repo }}
        PR_NUMBER: ${{ inputs.github_pr_number }}
        PR_TITLE: ${{ inputs.github_pr_title }}
        GH_TOKEN: ${{ inputs.github_token }}
        CURRENT_LABELS: ${{ steps.get_labels.outputs.labels }}

    - name: Add labels
      shell: bash
<<<<<<< HEAD
      working-directory: src/labels
      run: ./set.sh
=======
      run: |
        LABELS_TO_ADD=$( echo "${{ steps.get_labels.outputs.labels_to_add }}" | tr ' ' ',')
        echo LABELS_TO_ADD=$LABELS_TO_ADD

        gh pr edit $PR_NUMBER --repo $REPO --add-label $LABELS_TO_ADD

        CURRENT_PR_LABELS=$(gh pr view $PR_NUMBER --repo $REPO --json labels | jq -r '.labels[].name')
        LABELS_TO_DELETE=""

        echo CURRENT_PR_LABELS=$CURRENT_PR_LABELS

        for cur_label in $CURRENT_PR_LABELS
        do
            if ! [[ $LABELS_TO_ADD == *$cur_label* ]]; then
                if [[ $cur_label == *type/* || $cur_label == *component/* ]]; then
                  LABELS_TO_DELETE+=$cur_label,
                fi
            fi
        done

        LABELS_TO_DELETE=$(echo $LABELS_TO_DELETE | rev | cut -c2- | rev)

        echo LABELS_TO_DELETE=$LABELS_TO_DELETE

        if [ -n "$LABELS_TO_DELETE" ]; then
            gh pr edit $PR_NUMBER --repo $REPO --remove-label $LABELS_TO_DELETE
        fi

>>>>>>> 241d7e8 (lets move this out to another step)
      env:
        LABELS: ${{ steps.construct_labels.outputs.labels_to_add }}

    - name: Delete labels
      shell: bash
      run: gh pr edit $PR_NUMBER --repo $REPO --remove-label $LABELS_TO_DELETE
      env:
        LABELS_TO_DELETE: ${{ steps.construct_labels.outputs.labels_to_delete }}
        PR_NUMBER: ${{ inputs.github_pr_number }}
        REPO: ${{ inputs.github_owner }}/${{ inputs.github_repo }}
        GH_TOKEN: ${{ inputs.github_token }}

branding:
  icon: "message-square"
  color: "gray-dark"
