name: "Add Labels Action"
description: "Adds `type/...` and `component/...` labels by PR title using commitlint format and custom config."

inputs:
  github_owner:
    description: "Owner of the repository"
    default: ${{ github.repository_owner }}
  github_repo:
    description: "Repository name"
    default: ${{ github.event.repository.name }}
  github_token:
    description: "GitHub token"
    default: ${{ github.token }}
  github_pr_number:
    description: "GitHub PR number"
    default: ${{ github.event.pull_request.number }}
  github_pr_title:
    description: "GitHub PR title"
    default: ${{ github.event.pull_request.title }}

runs:
  using: "composite"
  steps:
    - name: Get current labels from PR
      id: get_labels
      shell: bash
      run: ${{ github.action_path }}/src/labels/get.sh
      env:
        REPO: ${{ inputs.github_owner }}/${{ inputs.github_repo }}
        PR_NUMBER: ${{ inputs.github_pr_number }}
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Construct labels to add/delete
      id: construct_labels
      shell: bash
      run: ${{ github.action_path }}/src/construct_labels.sh
      env:
        PR_TITLE: ${{ inputs.github_pr_title }}
        CURRENT_LABELS: ${{ steps.get_labels.outputs.labels }}

    - name: Add labels
      shell: bash
      run: ${{ github.action_path }}/src/labels/set.sh
      if: ${{ steps.construct_labels.outputs.labels_to_add != '' }}
      env:
        LABELS: ${{ steps.construct_labels.outputs.labels_to_add }}
        REPO: ${{ inputs.github_owner }}/${{ inputs.github_repo }}
        PR_NUMBER: ${{ inputs.github_pr_number }}
        GH_TOKEN: ${{ inputs.github_token }}

branding:
  icon: "tag"
  color: "gray-dark"
