name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  e2e-default:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set labels
        run: ./src/labels/set.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: |
            bug
            duplicate
            type/fix
            type/feat
            component/embeds
            component/auth
            component/docs

      - name: Test Run
        id: test-run
        uses: ./
        with:
          github_pr_title: "fix(docs, auth): test 123 mne grustno v shkole nevkusnaya kapusta"

      - name: Get labels
        id: get-labels
        run: ./src/labels/get.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assert placeholder
        uses: nick-fields/assert-action@22dd2a66ef733fe92022d3704183ac007463eecb # v3.0.0
        with:
          actual: ${{ steps.get-labels.outputs.labels }}
          expected: |
            bug
            component/auth
            component/docs
            duplicate
            type/fix

      - name: Delete all labels
        run: ./src/labels/delete_all.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-no-labels:
    runs-on: ubuntu-latest
    needs: e2e-default

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Test Run
        id: test-run
        uses: ./
        with:
          github_pr_title: "fix: esli b mishki bili b pchelami"

      - name: Get labels
        id: get-labels
        run: ./src/labels/get.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assert placeholder
        uses: nick-fields/assert-action@22dd2a66ef733fe92022d3704183ac007463eecb # v3.0.0
        with:
          actual: ${{ steps.get-labels.outputs.labels }}
          expected: |
            type/fix

      - name: Delete all labels
        run: ./src/labels/delete_all.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-with-single-label:
    runs-on: ubuntu-latest
    needs: [e2e-no-labels]

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set labels
        run: ./src/labels/set.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: |
            type/fix

      - name: Test Run
        id: test-run
        uses: ./
        with:
          github_pr_title: "fix: esli b mishki bili b pchelami"

      - name: Get labels
        id: get-labels
        run: ./src/labels/get.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assert placeholder
        uses: nick-fields/assert-action@22dd2a66ef733fe92022d3704183ac007463eecb # v3.0.0
        with:
          actual: ${{ steps.get-labels.outputs.labels }}
          expected: |
            type/fix

      - name: Delete all labels
        run: ./src/labels/delete_all.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
