name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  e2e-default:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set labels
        run: ./src/labels/set.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: "type/fix,type/feat,component/embeds,component/auth,component/docs,bug"

      - name: Test Run
        id: test-run
        uses: ./
        with:
          github_pr_title: "fix(docs, auth): test 123 mne grustno v shkole nevkusnaya kapusta"

      - name: Get labels
        id: get-labels
        run: ./src/labels/get.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assert placeholder
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.get-labels.outputs.labels }}
          expected: "bug,component/auth,component/docs,type/fix"

      - name: Delete all labels
        run: ./src/labels/delete_all.sh
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
